### ISSUE TITLE
Rid of Location Field and Import of IMEI and PhoneNumber/IP Address

### ISSUE THREAD

**Issue by bstieber12** [noahjahn/csmit-asset-manager#36]
We've all agreed in IT that the location field is not necessary for us to track. We should always be able to pin-point what we need based on the Owner and Team.

Two fields which are currently not visible are the IMEI field and PhoneNumber/IP Address field from Spiceworks. These two pieces of info are crucial for us to be able to get work done in our Verizon Portal.

**Comment by bstieber12** [comment]
In relation to the IMEI and PhoneNumber/IP Address fields -

Neither of them would need to be required fields, and neither of them would need to have a required format.

**Comment by noahjahn** [comment]
@bstieber12 did you guys use the IP Address field for phone numbers? Just wondering if I should only pull over data that are actually phone numbers in that field.
